services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: ./app
      dockerfile: ../php/Dockerfile
    volumes:
      - ./app:/var/www/html

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: supermarche
      MYSQL_USER: marche_user
      MYSQL_PASSWORD: sup_pass321
    ports:
      - "3307:3306"
